export const TODO_FETCH_REQUESTED = '@task/TODO_FETCH_REQUESTED'
export const TODO_FETCH_FAILED = '@task/TODO_FETCH_FAILED'
export const ADD_TASK = '@task/ADD_TASK'
export const REMOVE_TASK_BY_ID = '@task/REMOVE_TASK_BY_ID'
export const UPDATE_TASK_BY_ID = '@task/UPDATE_TASK_BY_ID'
